general:
  mode: "train"
  gpus: null
  seed: null
  ckpt_path: null # i.e. /home/fradlin/Github/Mask4D-Interactive/saved/2024-05-12_092821/last.ckpt
  project_name: Mask4D-Interactive
  workspace: Ilyafr97
  instance_population: 20
  dbscan_eps: null
  experiment_name: ${now:%Y-%m-%d_%H%M%S}-obj_type_${data.obj_type}-obj_count_${data.sample_choice}-max${general.max_num_clicks}clicks
  save_dir: saved/${general.experiment_name}
  visualization_dir: saved/${general.experiment_name}/pointclouds
  max_num_clicks: 5
  clicks_of_interest: [1, 2, 3, 4, 5] # another possibility [1, 3, 5, 10, 15, 20]
  iou_targets: [0.5, 0.65, 0.80, 0.85, 0.90]

defaults:
  - data: kitti
  - data/data_loaders: simple_loader
  - data/datasets: semantic_kitti
  - data/collation_functions: voxelize_collate
  - logging: full
  - model: interactive4d
  - optimizer: adamw
  - scheduler: onecyclelr
  - trainer: trainer30
  - callbacks: callbacks_panoptic
  - matcher: hungarian_matcher
  - loss: set_criterion
  - metric: lstq

hydra:
  run:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: saved/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${general.save_dir}
    subdir: ${hydra.job.num}_${hydra.job.id}
