# @package _group_
_target_: models.Interactive4D

# backbone
backbone:
  _target_: models.Res16UNet34C
  config:
    dialations: [1, 1, 1, 1]
    conv1_kernel_size: 5
    bn_momentum: 0.02
  in_channels: ${data.in_channels}
  out_channels: ${data.num_labels}

# transformer parameters
positional_encoding:
  _target_: models.position_embedding.PositionEmbeddingCoordsSine
  pos_type: "fourier"
  d_pos: ${model.hidden_dim}
  gauss_scale: 1.0
  normalize: True

num_heads: 8
num_decoders: 3
num_levels: 1
hidden_dim: 128
dim_feedforward: 1024
shared_decoder: False
num_bg_queries: 10
dropout: 0.0
pre_norm: False
aux: True
voxel_size: ${data.voxel_size}
sample_sizes: [4000, 8000, 16000, 32000]
# num_labels: ${data.num_labels}
