# @package _group_
criterion:
  _target_: models.criterion.SetCriterion
  # num_classes: ${data.num_labels}
  # eos_coef: 0.1
  losses:
    - "bce"
    - "dice"

aux: true
bce_loss_coef: 1.0
dice_loss_coef: 2.0
