# @package _group_
default_root_dir: ${general.save_dir}
profiler: simple
devices: 2
num_nodes: 1
accelerator: gpu
strategy: ddp_find_unused_parameters_false
max_epochs: 30
check_val_every_n_epoch: 5
num_sanity_val_steps: 0
detect_anomaly: false
log_every_n_steps: 100
limit_train_batches: null
limit_val_batches: null
